### ISSUE TITLE
Muliggør forlængelse af booking X minutter/antal kvarterer før nuværende tid udløber

### ISSUE THREAD

**Issue by mathiser** [gedemagt/booking#27]
Flere har på peget dette problem.
Man klatrer fra eks. 12-15 med én booking. Først når klokken er 15.00 kan man forlænge sin booking, men der har man overskredet muligheden for at booke ny tid fra kl 15.00 og frem og derfor kan man først få fra 15.15 og frem. Derved opstår ét kvarter, hvor man ikke må opholde sig i klubben.

**Comment by gedemagt** [comment]
Den nemmest løsning er at lave et lave et interval x, således at en booking kun tæller med i antallet af aktive bookinger indtil sluttidspunk - x. Så kan man lave en ny booking i fx det sidste kvarter af sin nuværende booking.

Alternativt skulle man lave support for faktisk at forlænge en booking, men det vil kræve en del mere UI ændringer. 

Så jeg vil nok foreslå den første model.

**Comment by gedemagt** [comment]
Fixed by #29
